# Site settings
title: Philipp Neugebauer's developer blog
email: ppn@philippneugebauer.net
description: >
  Rails and Git enthusiast,
  Java developer,
  Database engineer
baseurl: ""
url: http://philippneugebauer.net
twitter_username: ppneugebauer
github_username:  philippneugebauer

# Build settings
markdown: kramdown
#highlighter: rouge
paginate: 5
