# Site settings
title: Philipp Neugebauer's developer blog
email: ppn@philippneugebauer.net
description: >
  Rails and Git enthusiast
baseurl: ""
url: http://blog.philippneugebauer.net
twitter_username: ppneugebauer
github_username:  philippneugebauer
permalink: "/:title"
gems:      [jekyll-paginate]
# Build settings
markdown: kramdown
#highlighter: rouge
paginate: 5
