# Site settings
title: Philipp Neugebauer's blog
email: ppn@philippneugebauer.net
description: >
  Whatever's in my mind
baseurl: ""
url: http://philippneugebauer.net
twitter_username: ppneugebauer
github_username:  philippneugebauer
permalink: "/:title"
gems:      [jekyll-paginate]
# Build settings
markdown: kramdown
#highlighter: rouge
paginate: 5
