# Site settings
title: Philipp Neugebauer's developer blog
email: ppn@philippneugebauer.net
description: >
  Rails and Git enthusiast,
  Java developer,
  Database engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://philippneugebauer.net" # the base hostname & protocol for your site
twitter_username: ppneugebauer
github_username:  philippneugebauer

# Build settings
markdown: kramdown
#highlighter: rouge
paginate: 5
